services:
  attacker:
    build: ./attacker
    container_name: attacker
    ports:
      - "8001:8001"
    networks:
      - ddos_net

  ddos_client:
    build: ./ddos_client
    image: ddos_client_image
    cap_add:
      - NET_RAW
    cpu_period: 100000
    cpu_quota: 10000
    mem_limit: 64m
    depends_on: 
      - attacker
      - server
    environment:
      - ATTACKER_HOST=attacker
      - ATTACKER_API_PORT=8001
    networks:
      - ddos_net

  server:
    build: ./server
    sysctls:
      net.ipv4.tcp_syncookies: "0"
      net.ipv4.tcp_max_syn_backlog: "5"
      net.core.somaxconn: "5"
      net.ipv4.ipfrag_high_thresh:  26214400  
      net.ipv4.ipfrag_low_thresh:   19660800
      net.ipv4.ipfrag_time:         30      
    cpu_quota: 100000
    mem_limit: 64m
    ulimits:
      nproc: 1024
      nofile:
        soft: 1024
        hard: 2048
    container_name: ddos_server
    ports:
      - "12345:12345/tcp"
      - "12345:12345/udp"
    cap_add:
      - NET_ADMIN       
      - NET_RAW              
    networks:
      - ddos_net

  client1:
    build: ./client
    container_name: real_client1
    environment:
      - CLIENT_ID=1
      - PROTOCOL=udp
      - SERVER_HOST=server
    depends_on:
      - server
    networks:
      - ddos_net
    stdin_open: true
    tty: true

  client2:
    build: ./client
    container_name: real_client2
    environment:
      - CLIENT_ID=2
      - PROTOCOL=tcp
      - SERVER_HOST=server
    depends_on:
      - server
    networks:
      - ddos_net
    stdin_open: true
    tty: true

networks:
  ddos_net:
    driver: bridge