version: '3.8'
services:
  server:
    build: ./server
    cpu_quota: 50000
    mem_limit: 512m
    ulimits:
      nproc: 1024
      nofile:
        soft: 1024
        hard: 2048
    container_name: ddos_server
    ports:
      - "12345:12345/tcp"
      - "12345:12345/udp"
    cap_add:
      - NET_ADMIN                     
    networks:
      - ddos_net

  client1:
    build: ./client
    container_name: real_client1
    environment:
      - CLIENT_ID=1
      - PROTOCOL=udp
      - SERVER_HOST=server
    depends_on:
      - server
    networks:
      - ddos_net
    stdin_open: true
    tty: true

  client2:
    build: ./client
    container_name: real_client2
    environment:
      - CLIENT_ID=2
      - PROTOCOL=tcp
      - SERVER_HOST=server
    depends_on:
      - server
    networks:
      - ddos_net
    stdin_open: true
    tty: true

networks:
  ddos_net:
    driver: bridge
